Newsweek
Ramon-Carrillo/Newsweek pull request #1
Opened 2020-09-24 22:19 UTC by Ramon-Carrillo

Worked solo on this project. I finished the project and applied Bootstrap, HTML, and CSS. I would like you to make a review of my work.

2020-09-24 22:27 UTC, jubaan requested changes
# Status: INVALID :yellow_circle: 

Please follow the instructions to add the specific linters for the repository. Here is the link:

- [ ] [html-css](https://github.com/microverseinc/linters-config)

Please work on these things also:

- [ ] Professional repository, the one the project has is not descriptive enough.
- [ ] Better Pull Request message

## Happy coding! :smiley:

2020-09-24 22:43 UTC, Ramon-Carrillo commented
Added linters ask requested for a valid pull request review.

2020-09-25 00:29 UTC, teekaytech requested changes
## Status: Changes Required :warning::vertical_traffic_light: 

### Hello @Ramon-Carrillo :wave: 

**I must say, you've done an awesome job right here :clap:**
- Your linters are green :green_circle: 
- Good understanding of the project :heavy_check_mark: 

**In summary, this project is looking good and is almost complete. Talking about the completeness, there are some issues we need to fix before this project can be approved. Let's get to it:**

**[ REQUIRED CHANGES ]**
_As the main point of this project is to use Bootstrap, I will focus on this aspect in this code review_
- [ ] Your readme is not detailed enough. Check my comments below on what to do to make it better.

![00:45:16](https://user-images.githubusercontent.com/26856491/94211090-68008400-fec8-11ea-9765-e653c62c90b6.png)

- [ ] You used a lot of CSS bad practices in your project.
- You have a lot of repetitions in your CSS file. Kindly review your CSS rules and group the common blocks together.
- You overused the `!important` rule. Kindly find another way to make things work without the rule.
- Some of the duplications are highlighted below. Fix them and the rest.

![00:43:32](https://user-images.githubusercontent.com/26856491/94211055-50c19680-fec8-11ea-9e36-3478c460eb41.png)

- [ ] This is a bootstrap project. You are expected to use bootstrap classes as much as possible. 
- You can drastically reduce the size of your CSS file by using bootstrap classes for rules like margins, paddings, colors, and other styles.
- Using media queries in this project is not bad, but if bootstrap can do it, you should use bootstrap.

![00:39:24](https://user-images.githubusercontent.com/26856491/94210775-95006700-fec7-11ea-8d43-54df1eb7d1b1.png)

- [ ] Your navigation bar should contain the current date
__Original navbar__
![00:48:07](https://user-images.githubusercontent.com/26856491/94211246-d2192900-fec8-11ea-803e-03a962d9782a.png)

__Your navbar__
![00:47:54](https://user-images.githubusercontent.com/26856491/94211264-df361800-fec8-11ea-86da-3aca01b8c42d.png)

- [ ] Adjust newsletter section for medium screen devices 

Original page

![01:09:45](https://user-images.githubusercontent.com/26856491/94212422-0f32ea80-fecc-11ea-9840-331fba08f2e4.png)

Your clone

![01:09:18](https://user-images.githubusercontent.com/26856491/94212443-16f28f00-fecc-11ea-8c5d-2e5e8a79852f.png)

**Small devices**
- [ ] The top stories section is followed by the featured stories section in the original. This is not the case in your clone page. Kindly rearrange it.

- [ ] Kindly re-structure your more stories section

Original page
![01:20:07](https://user-images.githubusercontent.com/26856491/94212913-64bbc700-fecd-11ea-8344-9c3b7e613c5e.png)

Your clone

![01:18:55](https://user-images.githubusercontent.com/26856491/94212925-6c7b6b80-fecd-11ea-81c0-0b3459e68f58.png)

- [ ] Editors' pick section also needs some re-adjustments

Original page
![01:24:22](https://user-images.githubusercontent.com/26856491/94213164-16f38e80-fece-11ea-8f01-8deef46076eb.png)

Your clone 

![01:25:20](https://user-images.githubusercontent.com/26856491/94213189-21158d00-fece-11ea-9c16-dc2398efb68d.png)

**Please note: You are asked to be more precise and to make sure that your page looks exactly the same as the source page.**

Kindly make the required changes and request for another review when you are done.

*__You can reach out to me on slack (@taofeekolalere) or GitHub (@teekaytech).__*

**Happy coding. :man_technologist:**

2020-09-28 23:39 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-09-28 23:52 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Ramon-Carrillo
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.

- [x] Follow the adustment suggestions
- [x] Remove `!important `from css file. ([Article for support](https://speckyboy.com/good-bad-css-practices/)) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright)

- [x] make sure the order of sections on small screens



### Navbar (medium screen)
- [x] Replace **SIGN IN** with user icon
- [x] Remove the search text from navbar

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://ramon-carrillo.github.io/Newsweek/)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/94496527-16c8fb00-020e-11eb-9f5d-5c03b4fc801d.png)|![clone](https://user-images.githubusercontent.com/29689273/94496549-234d5380-020e-11eb-8e3f-376cf73cde5f.png)|



### Navbar (small screen)
- [x] Replace **SIGN IN** with user icon
- [x] Display **SUBSCRIBE** button

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://ramon-carrillo.github.io/Newsweek/)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/94496564-2a746180-020e-11eb-9200-643aaf4f8ecc.png)|![clone](https://user-images.githubusercontent.com/29689273/94496536-1c264580-020e-11eb-8e5b-a24177ef1217.png)|

### SUBSCRIBE
- [ ] Text should be overflow on images in small screens

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://ramon-carrillo.github.io/Newsweek/)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/94496691-83dc9080-020e-11eb-86a1-f47998bc27e3.png)|![clone](https://user-images.githubusercontent.com/29689273/94496696-86d78100-020e-11eb-9419-7c2d2845c83f.png)|


##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-28 23:52 UTC, umairarshadbutt commented on css/style.css
> +  visibility: visible !important;
Remove `!important`

2020-09-28 23:52 UTC, umairarshadbutt commented on css/style.css
> +    align-self: flex-end !important;
Remove `!important`

2020-09-28 23:52 UTC, umairarshadbutt commented on css/style.css
> +    align-self: flex-end !important;
Remove `!important`

2020-09-29 12:57 UTC, Ramon-Carrillo commented
Made adjustments that were requested in the last pull request. I added a user icon, fixed breakpoint, and reorder the order.

2020-09-29 13:06 UTC, arslanbisharat approved these changes
### Congratulations APPROVED :clap:
Hello I can see you worked really hard on this project. and I'm very happy to approve this project with the latest changes you made in this project. :satisfied:
_The clone shows a good understanding and usage of HTML CSS💯_

- The cloned page is rendering as it should and meets all the project specifications.
-  CSS is clean.
-  The markup as well has no errors nor warnings to show. Good job with that.
-  The repo has followed all the guidelines there are to follow.
-  All the required tasks have been fulfilled in this project.
-  Congratulations on the splendid job👍
Now you can merge the branches and move forward with your curriculum. 🎆 

- [ ] Optional Please add some description in about section of your repo

- [ ] Please add all images and CSS files in a single folder

- [ ] Please add more description in the readme file. 

[OPTIONAL] If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 

I am very excited to see your next project.

**Happy Coding**:smiley:
------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) slack: @arslanbisharat

2020-10-14 02:35 UTC, merged